2nd_session/ex_2nd_session/ex_2nd_session/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main.urls')),
    path('', include('accounts.urls')),
    path('', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

2nd_session/ex_2nd_session/main/urls.py
from django.urls import path
from .views import *

app_name = "main"
urlpatterns = [
    path('', mainpage, name="mainpage"),
    path('intro/', interestpage, name='interestpage'),
    path('new/', new, name="new"),
    path('create/', create, name="create"),
    path('post/', post, name='post'),
    path('<int:id>', detail, name="detail"),
    path('edit/<int:id>', edit, name='edit'),
    path('update/<int:id>', update, name="update"),
    path('delete/<int:id>', delete, name="delete"),
    path('tag/', tag_list, name="tag_list"),
    path('tag/<int:tag_id>', tag_posts, name="tag_posts"),
    path('delete_com/<int:id>', delete_com, name="delete_com"),
    path('likes/<int:post_id>', likes, name="likes"),
    # img urls
    # path('edit_img/<int:id>', edit_img, name="edit_img"),
    # path('update_img/<int:id>', update_img, name="update_img"),
    # path('delete_img/<int:id>', delete_img, name="delete_img"),
]

2nd_session/ex_2nd_session/users/urls.py
from django.urls import path
from .views import *

app_name = "users"

urlpatterns = [
   path('mypage/<int:id>', mypage, name="mypage"),
   path('follow/<int:id>', follow, name="follow"),
]

2nd_session/ex_2nd_session/users/models.py
from django.db import models

# Create your models here.

2nd_session/ex_2nd_session/users/views.py
from django.shortcuts import render,redirect, get_object_or_404
from main.models import Post
from django.contrib.auth.models import User

# Create your views here.
def mypage(request, id):
    user = get_object_or_404(User, pk=id)
    context = {
        'user':user,
        'posts':Post.objects.filter(writer=user),
        'followings': user.profile.followings.all(),
        'followers': user.profile.followers.all(),
    }
    return render(request, 'users/mypage.html', context)

def follow(request, id):
    user = request.user
    followed_user = get_object_or_404(User, pk=id)
    is_follower = user.profile in followed_user.profile.followers.all()
    if is_follower:
        user.profile.followings.remove(followed_user.profile)
    else:
        user.profile.followings.add(followed_user.profile)
    return redirect('users:mypage', followed_user.id)

2nd_session/ex_2nd_session/users/templates/users/mypage.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="content">
    <h3>{{ user.profile.nickname }}님 안녕하세요. </h3>
    <h3>학과는 {{user.profile.department}} 입니다.</h3>
    <h3>번호는 {{user.profile.phone}} 입니다.</h3>

    {% if request.user != user %}
        {% if request.user.profile in user.profile.followers.all %}
            <a href="{% url 'users:follow' user.id %}"><button type="button"> 언팔로우 </button></a>
        {% else %}
            <a href="{% url 'users:follow' user.id %}"><button type="button"> 팔로우 </button></a>
        {% endif %}
    {% endif %}

    <p>팔로워 <br> {{user.profile.followers.count }}명</p>
    {% for follower in user.profile.followers.all %}
        <a href="{% url 'users:mypage' follower.user.id %}">{{ follower.user.name }}</a>
    {% endfor %}

    <p>팔로잉 <br> {{user.profile.followings.count }}명</p>
    {% for following in user.profile.followings.all %}
        <a href="{% url 'users:mypage' following.user.id %}">{{ following.user.name }}</a>
    {% endfor %}

</div>

{% endblock %}