2nd_session/ex_2nd_session/ex_2nd_session/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main.urls')),
    path('', include('accounts.urls')),
    path('', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

2nd_session/ex_2nd_session/main/urls.py
from django.urls import path
from .views import *

app_name = "main"
urlpatterns = [
    path('', mainpage, name="mainpage"),
    path('intro/', interestpage, name='interestpage'),
    path('new/', new, name="new"),
    path('create/', create, name="create"),
    path('post/', post, name='post'),
    path('<int:id>', detail, name="detail"),
    path('edit/<int:id>', edit, name='edit'),
    path('update/<int:id>', update, name="update"),
    path('delete/<int:id>', delete, name="delete"),
    path('tag/', tag_list, name="tag_list"),
    path('tag/<int:tag_id>', tag_posts, name="tag_posts"),
    path('delete_com/<int:id>', delete_com, name="delete_com"),
    path('likes/<int:post_id>', likes, name="likes"),
    # img urls
    # path('edit_img/<int:id>', edit_img, name="edit_img"),
    # path('update_img/<int:id>', update_img, name="update_img"),
    # path('delete_img/<int:id>', delete_img, name="delete_img"),
]

2nd_session/ex_2nd_session/users/urls.py
from django.urls import path
from .views import *

app_name = "users"

urlpatterns = [
   path('mypage/<int:id>', mypage, name="mypage"),
   path('follow/<int:id>', follow, name="follow"),
]

2nd_session/ex_2nd_session/main/models.py
from django.db import models
from django.contrib.auth.models import User

class Tag(models.Model):
    name=models.CharField(max_length=30, null=False, blank=False)

    def __str__(self) -> str:
        return self.name
    
class Post(models.Model):
    title = models.CharField(max_length=200)
    writer = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE)
    # writer = models.CharField(max_length=100)
    pub_date = models.DateTimeField()
    weather = models.CharField(max_length=50)
    mood = models.CharField(max_length=50)
    body = models.TextField()
    image = models.ImageField(upload_to="blog/", blank=True, null=True)
    tags = models.ManyToManyField(Tag, related_name='posts', blank=True)
    like = models.ManyToManyField(User, related_name='likes', blank=True)
    like_count = models.PositiveIntegerField(default=0)
    
    def __str__(self):
        return self.title
    
    def summary(self):
        return self.body[:20]
    
class Comment(models.Model):
    content = models.TextField()
    pub_date = models.DateTimeField()
    writer = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, null=False, blank=False, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, related_name='comments', blank=True)

    def __str__(self):
        return self.post.title

2nd_session/ex_2nd_session/main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, Comment, Tag
from django.utils import timezone
from django.db.models import Q

# Create your views here.

def mainpage(request):
    return render(request, 'main/mainpage.html')

def interestpage(request):
    return render(request, 'main/interestpage.html')

def new(request):
    return render(request, 'main/new.html')

def post(request):
    posts = Post.objects.all()
    return render(request, 'main/post.html', {'posts':posts})

def create(request):    # 데이터베이스에 저장하는 함수
    if request.user.is_authenticated:   # 로그인 되어 있으면 게시글 저장
        new_post = Post()
        new_post.title = request.POST['title']
        # 현재 로그인 한 유저
        new_post.writer = request.user
        new_post.pub_date = timezone.now()
        new_post.weather = request.POST['weather']
        new_post.mood = request.POST['mood'] 
        new_post.body = request.POST['body']
        new_post.image = request.FILES.get('image')
        new_post.save()
        # 본문 내용을 띄어쓰기로 잘라냄
        words = new_post.body.split(' ')
        tag_list = []
        for w in words:
            if len(w)>0 and w[0]=='#':
                tag_list.append(w[1:])
        for t in tag_list:
            tag, boolean = Tag.objects.get_or_create(name=t)
            new_post.tags.add(tag.id)
        return redirect('main:detail', new_post.id)
    else:
        return redirect('accounts:login')

def detail(request, id):
    post = get_object_or_404(Post, pk = id)
    if request.method == 'GET':
        comments = Comment.objects.filter(post=post)
        return render(request, 'main/detail.html', {
            'post':post,
            'comments':comments,
            })
    elif request.method == "POST":
        new_comment = Comment()
        new_comment.post = post
        new_comment.writer = request.user
        new_comment.content = request.POST['content']
        new_comment.pub_date = timezone.now()
        new_comment.save()
        words = new_comment.content.split(' ')
        tag_list = []
        for w in words:
            if len(w)>0 and w[0]=='#':
                tag_list.append(w[1:])
        for t in tag_list:
            tag, boolean = Tag.objects.get_or_create(name=t)
            new_comment.tags.add(tag.id)
        return redirect('main:detail', id)
    
def delete_com(request, id):
    delete_com = Comment.objects.get(id=id)
    if request.user == delete_com.writer:
        delete_com.delete()
    return redirect('main:post')

def edit(request, id):
    edit_post = Post.objects.get(id=id)
    return render(request, 'main/edit.html', {'post':edit_post })

def update(request, id):
    if request.user.is_authenticated:
        update_post = Post.objects.get(id=id)
        if request.user == update_post.writer:
            update_post.title = request.POST['title']
            update_post.writer = request.user
            update_post.pub_date = timezone.now()
            if request.FILES.get('image'):
                update_post.image = request.FILES.get('image')
            else: 
                update_post.image = update_post.image
            update_post.weather = request.POST['weather']
            update_post.mood = request.POST['mood'] 
            update_post.body = request.POST['body']
            update_post.save()
            # 태그 수정
            words = update_post.body.split(' ')
            tag_list = []
            for w in words:
                if len(w)>0 and w[0]=='#':
                    tag_list.append(w[1:])

            update_post.tags.clear()    # 원래 있던 tag필드 삭제
            # 이렇게 되면 post.tags는 없어지는데 Tag의 내용은 안없어지네
            for t in tag_list:
                tag, boolean = Tag.objects.get_or_create(name=t)
                update_post.tags.add(tag.id)
            return redirect('main:detail', update_post.id)
    return redirect('accounts:login')

def delete(request, id):
    delete_post = Post.objects.get(id=id)
    delete_post.delete()
    return redirect('main:post')


def tag_list(reqeust):
    tags = Tag.objects.all()
    return render(reqeust, 'main/tag_list.html',{
        'tags':tags,
    })

def tag_posts(request, tag_id):
    tag = get_object_or_404(Tag, id=tag_id)
    posts = Post.objects.filter(Q(tags=tag) | Q(comment__tags=tag)).distinct()

    # 이쪾 건드리면 과제 구현할 수 있을 거같은데
    return render(request, 'main/tag_posts.html', {
        'tag':tag,
        'posts':posts,
    })

def likes(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user in post.like.all():
        post.like.remove(request.user)
        post.like_count -= 1
        post.save()
    else:
        post.like.add(request.user)
        post.like_count += 1
        post.save()
    return redirect('main:detail', post.id)

# def delete_img(request, id):
#     delete_img_post = Post.objects.get(id=id)
#     delete_img_post.image.delete(save=True)
#     return redirect('main:detail', delete_img_post.id)

# def edit_img(request, id):
#     edit_img_post = Post.objects.get(id=id)
#     return render(request, 'main/editimg.html', {'post':edit_img_post})

# def update_img(request, id):
#     update_img_post = Post.objects.get(id=id)
#     update_img_post.image = request.FILES.get('image')
#     update_img_post.save()
#     return redirect('main:detail', update_img_post.id)
    

2nd_session/ex_2nd_session/main/templates/main/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="detail_post"> 

    <h1>{{post.title}}</h1>
    작성자 : <a href="{% url 'users:mypage' post.writer.id %}">{{post.writer}}</a> <br>
    날짜 : {{post.pub_date}} <br>
    날씨 : {{post.weather}} <br>
    오늘의 상태 : {{post.mood}}
    <hr>
    {% if post.image %}
        <p><img src="{{post.image.url}}" alt="사진"></p>
    {% else %}
        <p>!!!사진을 등록해주세요!!!</p>
    {% endif %}
    <p>{{post.body}}</p>
    <p>태그 : <!-- {post.tags.all|join:", "}-->
        {% for tag in post.tags.all %}
        <a href="{% url 'main:tag_posts' tag.pk %}">{{ tag.name }}</a>
        {% endfor %}
    </p>
    {% if post.writer == user %}
    <a href="{% url 'main:edit' post.id %}">수정하기</a>
    <a href="{% url 'main:delete' post.id %}">삭제하기</a>
    {% endif %}
    <hr>

    <a href="{% url 'main:likes' post.id %}">
        {% if user in post.like.all %}
        취소
        {% else %}
        좋아요
        {% endif %}
    </a>
    {{post.like_count}}개
    <hr>

    <h2>댓글 작성하기</h2>
    <form method="POST" action="{% url 'main:detail' post.id %}" >
        {%csrf_token%}
        <input type="text" name="content">
        <input type="submit" name="submit">
    </form>
    {% for c in comments %}
    <h4>작성자 : {{c.writer}}</h4>
    <p>내용 : {{c.content}} </p>
    <p>{{c.pub_date}}</p>
    <p>태그 : 
        {% for tag in c.tags.all %}
        <a href="{% url 'main:tag_posts' tag.pk %}">{{ tag.name }}</a>
        <hr>
        {% endfor %}
    </p>
    {% if c.writer == user %}
    <a href="{% url 'main:delete_com' c.id%}">댓글삭제</a>
    {% endif %}

    {% endfor %}
</div>
    

{% endblock %}

2nd_session/ex_2nd_session/main/templates/main/edit.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="content">
    <h1>글 수정하기</h1>
    <form action="{% url 'main:update' post.id %}" method="post" enctype="multipart/form-data">
        {%csrf_token%}
        <p>제목 : <input type="text" name="title" value="{{post.title}}"></p>
        <p>작성자 : <input type="text" name="writer" value="{{post.writer}}"></p>
        {% if post.image %}
            <img src="{{post.image.url}}" alt="사진">
        {% endif %}
        <p>수정할 사진을 선택해주세요</p>
        <p>사진 : <input type="file" name="image" ></p>
        <p>날씨 : <input type="text" name="weather" value="{{post.weather}}"></p>
        <p>오늘의 상태 : <input type="text" name="mood" value="{{post.mood}}"></p>
        <p>내용 : <textarea name="body" id="" cols="30" rows="10" >{{post.body}}</textarea></p>
        <button type="submit">제출</button>
    </form>
</div>
{% endblock %}

2nd_session/ex_2nd_session/main/templates/main/interestpage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="interest_img">
  <h1>What I Like</h1>

  <img src="{% static 'images/cloud.jpeg' %}">
  <img src="{% static 'images/cat.jpeg' %}">
  <img src="{% static 'images/dog.jpeg' %}">
  <img src="{% static 'images/travel.jpeg' %}">
  <img src="{% static 'images/band.jpeg' %}">
  <img src="{% static 'images/star.jpeg' %}">

</div>


{% endblock %}

2nd_session/ex_2nd_session/main/templates/main/mainpage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="content">

  <img src="{% static 'images/mimo.png' %}" alt="mimo" style="width:300px">
  <h1 class="title">
    Hi there, I am ByungHyun <br>
  </h1>
  <h3>
    안녕하세요! 멋쟁이사자처럼 11기 BackEnd 전병현입니다.<br>
    산업공학과지만 코딩과 개발에 흥미를 느껴 <br>
    IT 창업을 목표로 도전하고 있습니다. <br>
  </h3>

  <p>
    Phone : 010-2637-3087 <br>
    Email : qudgus0522@gmail.com <br>
    Instagram : @j_00bh
  </p>
  
</div>




{% endblock %}

2nd_session/ex_2nd_session/main/templates/main/new.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="post">

<h1>글 작성</h1>
<form action="{% url 'main:create' %}" method="POST" enctype="multipart/form-data">
    {%csrf_token%}
    <p>제목 : <input type="text" name="title"></p>
    <!-- <p>작성자 : <input type="text" name="writer"></p>   -->
    <p>사진 : <input type="file" name="image"></p>
    <p>날씨 : <input type="text" name="weather"></p>
    <p>오늘의 상태 : <input type="text" name="mood"></p>
    <p>내용 : <textarea type="text" name="body" id="" cols="30" rows="10"></textarea></p>
    <button type="submit">제출</button>
</form>

</div>


{% endblock %}

2nd_session/ex_2nd_session/main/templates/main/post.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="post">
    <h1>글 목록</h1>
    {% for post in posts %}
    <div>
        <h3>{{post.title}}</h3>
        {{post.writer}} {{post.weather}} {{post.mood}} <br>
        {{post.summary}}
        <a href="{%url 'main:detail' post.id%}">...자세히</a>
        <hr>
    </div>
    {% endfor %}
</div>

{% endblock %}

2nd_session/ex_2nd_session/main/templates/main/tag_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="content">
    <h1>해시태그 목록</h1>
    <hr>
    {% for t in tags %}
    <div class="tag">
        <h2 class="title"><a href="{% url 'main:tag_posts' t.id %}">#{{t.name}}</a></h2>
    </div>
    <hr>
    {% endfor %}
</div>

{% endblock %}

2nd_session/ex_2nd_session/main/templates/main/tag_posts.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="content">
    <h1>#{{tag}} 게시물 목록</h1>
    <hr>
    {% for b in posts %}
    <div class="post">
        <h2 class="title"><a href="{% url 'main:detail' b.id %}">제목 : {{ b.title }}</a></h2>
        <h4>작성자 : {{ b.writer }}</h4>
        <p>내용 : {{ b.body }}</p>
    </div>
    <hr>
    {% endfor %}
</div>

{% endblock %}