2nd_session/ex_2nd_session/accounts/urls.py
from django.urls import path
from .views import *

app_name = "accounts"

urlpatterns = [
    path('login/', login, name="login"),
    path('logout/', logout, name="logout"),
    path('signup/', signup, name="signup"),
]

2nd_session/ex_2nd_session/ex_2nd_session/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main.urls')),
    path('', include('accounts.urls')),
    path('', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

2nd_session/ex_2nd_session/main/urls.py
from django.urls import path
from .views import *

app_name = "main"
urlpatterns = [
    path('', mainpage, name="mainpage"),
    path('intro/', interestpage, name='interestpage'),
    path('new/', new, name="new"),
    path('create/', create, name="create"),
    path('post/', post, name='post'),
    path('<int:id>', detail, name="detail"),
    path('edit/<int:id>', edit, name='edit'),
    path('update/<int:id>', update, name="update"),
    path('delete/<int:id>', delete, name="delete"),
    path('tag/', tag_list, name="tag_list"),
    path('tag/<int:tag_id>', tag_posts, name="tag_posts"),
    path('delete_com/<int:id>', delete_com, name="delete_com"),
    path('likes/<int:post_id>', likes, name="likes"),
    # img urls
    # path('edit_img/<int:id>', edit_img, name="edit_img"),
    # path('update_img/<int:id>', update_img, name="update_img"),
    # path('delete_img/<int:id>', delete_img, name="delete_img"),
]

2nd_session/ex_2nd_session/users/urls.py
from django.urls import path
from .views import *

app_name = "users"

urlpatterns = [
   path('mypage/<int:id>', mypage, name="mypage"),
   path('follow/<int:id>', follow, name="follow"),
]

2nd_session/ex_2nd_session/ex_2nd_session/templates/shared/_navbar.html
<nav>

  <ul class="nav">
    <li><a href="{% url 'main:mainpage' %}">HOME</a></li>
    <li><a href="{% url 'main:interestpage' %}">INTEREST</a></li>
    <li><a href="{% url 'main:post' %}">POST</a></li>
  {% if user.is_authenticated %}
    <li><a href="{% url 'main:new' %}">WRITE</a></li>
    <li><a href="{% url 'users:mypage' user.id %}">mypage</a></li>
    <li><a href="{% url 'main:tag_list' %}">TAGS</a></li>
    <li>{{user.username}}</li>
    <li><a href="{% url 'accounts:logout' %}">로그아웃</a></li>
  {% else %}
    <li><a href="{% url 'accounts:login' %}">login</a></li>
    <li><a href="{% url 'accounts:signup' %}">signup</a></li>
  {%endif%}
  </ul>

</nav>